# Generated by Django 4.0.4 on 2022-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_img',
            field=models.CharField(default='https://kimerahome.com/wp-content/uploads/2020/08/Product-Placeholder.jpg', max_length=500),
        ),
    ]
